from aviary.models.engines.propulsion.prop.propeller_empirical_mm import EmpiricalPropellerCoeffMM
from aviary.models.engines.propulsion.prop.propeller_data import PropellerData
from aviary.models.engines.propulsion.prop.propeller_empirical_mtip_mm import EmpiricalPropellerCoeffMMMtip