from .motor_empirical_mm import EmpiricalMotor
from .h3x_motor_data_rfi import MotorDataPowerEffCurve
from .h3x_motor_data_web import MotorDataEffMap, MotorDataPowerVoltCurve
from .h3x_rubber import MotorDataThrottleEffCurve
from .motor_rubber_mm import RubberMotor