# Power train configuration dictionary for E1700
import numpy as np
from aviary.models.aircraft.e180.check_mission_config import check_mission_config
 
phase_names = ["taxi", "takeoff","climb_e","climb_hy","cruise_1","cruise_2","descent","circuit", 
               "approach", "reserve_go_around","reserve_climb", "reserve_cruise",
               "reserve_descent","reserve_circuit","reserve_approach","reserve_taxi_in", "holding_cruise"]

#phase_names = ["taxi", "takeoff","climb_e","climb_hy","cruise_1", "descent","circuit", "approach",
#               "reserve_go_around", "reserve_climb", "reserve_cruise", "reserve_descent"]


def get_mission_config(nn, num_props=4, reserve_type="EASA", pow_ratings=None, 
turb_op=[1,0,0,0], opt_objective = "range", opt_mission = False):

    nac_max_cont_pow_throttle = pow_ratings["nacelle"]["MCP"]["throttle"]
    nac_max_cont_pow_val = pow_ratings["nacelle"]["MCP"]["value"]
    nac_max_cont_pow_units = pow_ratings["nacelle"]["MCP"]["units"]
    nac_max_rated_pow_val = pow_ratings["nacelle"]["MTOP"]["value"]
    nac_max_rated_pow_units = pow_ratings["nacelle"]["MTOP"]["units"]

    gt_max_cont_pow_throttle = pow_ratings["turbine"]["MCP"]["throttle"]
    gt_max_cont_pow_val = pow_ratings["turbine"]["MCP"]["value"]
    gt_max_cont_pow_units = pow_ratings["turbine"]["MCP"]["units"]

    em_max_cont_pow_throttle = pow_ratings["motor"]["MCP"]["throttle"]
    em_max_cont_pow_val = pow_ratings["motor"]["MCP"]["value"]
    em_max_cont_pow_units = pow_ratings["motor"]["MCP"]["units"]

    em_mtop_pow_throttle = pow_ratings["motor"]["MTOP"]["throttle"]
    em_mtop_pow_val = pow_ratings["motor"]["MTOP"]["value"]
    em_mtop_pow_units = pow_ratings["motor"]["MTOP"]["units"]


    if reserve_type == "EASA":
        hld_crz_h_ft = 1500
        hld_crz_dur_min = 30
    elif reserve_type == "FAA":
        hld_crz_h_ft = 8000
        hld_crz_dur_min = 45


    if sum(turb_op) == 4 or sum(turb_op) == 0:
        cruise1_rule = "fraction"
    else:
        cruise1_rule = "fixed"
    # end 
    #cruise1_rule = "fraction"

    

    if sum(turb_op) ==4:
        climb_pow_start_kW = nac_max_cont_pow_val
        climb_pow_end_kW = nac_max_cont_pow_val
        mission_range_nm = 275
    else:
        if sum(turb_op) == 0:
            mission_range_nm = 90
        else:
            mission_range_nm = 275
        climb_pow_start_kW = 1150
        climb_pow_end_kW = 1100

    if opt_mission:
        if opt_objective == "range":
            cruise1_duration_set = True
            cruise1_match_range = False
            cruise2_duration_set = True
            cruise2_match_range = False
        elif opt_objective == "fuel":
            cruise1_duration_set = False
            cruise1_match_range = True
            cruise2_duration_set = True
            cruise2_match_range = False
    else:
        # Default values when not optimizing mission
        # TOOD: Add another flag for this...
        cruise1_duration_set = True
        cruise1_match_range = False
        cruise2_duration_set = True
        cruise2_match_range = False

    mission_config = {
        "mission":{
            "range": {"value": mission_range_nm, "units": "NM"},
            "phase_names": phase_names,
            "soc_target": 0.123,
            "min_voltage_target": 570,
            "cruise_duration": {"value": 4, "units": "min"},
            "hy_cruise_t_ratio": {"value": 0.975, "units": None},
            #"e_cruise_d_ratio": {"value": 0.005, "units": None},
        },
        "reserve": {
            "range": {"value": 100.0, "units": "NM"},
            
        },
        "taxi": { # TAXI
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": False,  # Optimize power control via smoothstep (var_name: phase|total_mech_power_out)
                "eq_power_nacelles_op": True,   # Same power control across all nacelles
                "const_power_profile": False,  # Constant power (True) or transient smoothstep (False)
                "s_curve_hy_profile": False,     # Optimize hybridization control via smoothstep (var_name: phase|hy_ratio)
                "eq_hy_nacelles_op": False,      # Same hybridization control across all nacelles
                "const_hy_ratio": False,    # Constant hybridization (True) or transient smoothstep (False)
                "prop": {
                    "prop_thrust_set": False,
                    "nacelle_power_set": True,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "relative",
                    "rule": "fraction",
                    "bias": "em",
                    "total_mech_power_out": {"value": 40 * np.ones((num_props,nn)), "units": "kW"},
                    "power_split_fraction_em": {"value": np.ones((num_props,nn)) * 1, "units": None},
                    #"power_split_fraction_gt": {"value": 0.5 * np.ones(nn), "units": None},
                    #"power_split_amount_em": {"value": 1000 * np.ones(nn), "units": "kW"},
                    #"power_split_amount_gt": {"value": 1000 * np.ones(nn), "units": "kW"},
                    #"rpm": {"value": 950 * np.ones(nn), "units": "rpm"},
                },
                "turbine": {
                    "control": "power",
                    "gt_idle_allowed": False,
                    #"gt_throttle": {"value": 0.5 * np.ones(nn), "units": None},
                    #"gt_power": {"value": 1000 * np.ones(nn), "units": "kW"},
                },
                "motor": {
                    "control": "power",
                    #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                    #"power": {"value": 1000 * np.ones(nn), "units": "kW"},
                    "rpm": {"value": np.ones((num_props,nn)) * 950, "units": "rpm"},
                },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "fltcond":{
                "vs": {"value": 0 * np.ones(nn), "units": "ft/min"},
                "Ueas": {"value": np.linspace(25,25,nn), "units": "kn"},
                #"Utrue": {"value": 60.0 * np.ones(nn), "units": "m/s"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 15 * np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "down", "units": None},
            },  
            "trajectory":{
                "range_initial": {"value": 0.0, "units": "NM"},
                "fuel_used_initial": {"value": 0.0, "units": "kg"},
                "soc_initial": {"value": 0.9, "units": None},
                "duration": {"value": 600, "units": "s"},
                "h0": {"value": 0, "units": "ft"},
                "h1": {"value": 0, "units": "ft"},
            },
            "use_neural_net": False,
            "match_alt": False,
            "match_speed": False,
            "match_range": False,
            "duration_set": True,
            "velocity_in": True,
            "power_in": True,
            "true_airspeed_in": False,
            "vs_in": True,
            "gamma_in": False,
            "point_analysis": False,
            "indep_nacelles": False,
            "phase_type": "power_only",
            "phase_name": "taxi",
            "speed_law": "transient",

        },
    
        "takeoff": { # TAKEOFF
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": False,
                "eq_power_nacelles_op": True,
                "const_power_profile": False,
                "s_curve_hy_profile": False,
                "eq_hy_nacelles_op": False,
                "const_hy_ratio": False,
                "prop": {
                    "prop_thrust_set": False,
                    "nacelle_power_set": True,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "relative",
                    "rule": "fraction",
                    "bias": "em",
                    "total_mech_power_out": {"value": em_mtop_pow_val * np.ones((num_props,nn)), "units": em_mtop_pow_units},
                    "power_split_fraction_em": {"value": 1 * np.ones((num_props,nn)), "units": None},
                    #"power_split_fraction_gt": {"value": 0.5 * np.ones(nn), "units": None},
                    #"power_split_amount_em": {"value": 1000 * np.ones(nn), "units": "kW"},
                    #"power_split_amount_gt": {"value": 1000 * np.ones(nn), "units": "kW"},
                },
                "turbine": {
                    "control": "power",
                    "gt_idle_allowed": False,
                    #"gt_throttle": {"value": 0.5 * np.ones(nn), "units": None},
                    #"gt_power": {"value": 1000 * np.ones(nn), "units": "kW"},
                },
                "motor": {
                    "control": "power",
                    #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                    #"power": {"value": 1000 * np.ones(nn), "units": "kW"},
                    "rpm": {"value": 1790 * np.ones((num_props,nn)), "units": "rpm"},
                },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "fltcond":{
                "vs": {"value": 0 * np.ones(nn), "units": "ft/min"},
                "Ueas": {"value": np.linspace(25,120,nn), "units": "kn"},
                #"Utrue": {"value": 60.0 * np.ones(nn), "units": "m/s"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 15 * np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "down", "units": None},
            },
            "trajectory":{
                "h0": {"value": 0, "units": "ft"},
                "h1": {"value": 35, "units": "ft"},
                "duration": {"value": 45, "units": "s"},
            },
            "use_neural_net": False,
            "match_alt": False,
            "match_speed": False,
            "match_range": False,
            "duration_set": True,
            "phase_type": "power_only",
            "velocity_in": True,
            "power_in": True,
            "true_airspeed_in": False,
            "vs_in": True,
            "gamma_in": False,
            "point_analysis": False,
            "indep_nacelles": True,
            "phase_name": "takeoff",
            "speed_law": "transient",
        },
    
    
        "climb_e": { # CLIMB E
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": False,
                "eq_power_nacelles_op": True,
                "const_power_profile": False,
                "s_curve_hy_profile": False,
                "eq_hy_nacelles_op": False,
                "const_hy_ratio": False,
                "prop": {
                    "prop_thrust_set": False,
                    "nacelle_power_set": True,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "relative",
                    "rule": "fraction",
                    "bias": "em",
                    "total_mech_power_out": {"value": em_max_cont_pow_val * np.ones((num_props,nn)), "units": "kW"},
                    "power_split_fraction_em": {"value": 1 * np.ones((num_props,nn)), "units": None},
                    #"power_split_fraction_gt": {"value": 0.5 * np.ones(nn), "units": None},
                    #"power_split_amount_em": {"value": 1000 * np.ones(nn), "units": "kW"},
                    #"power_split_amount_gt": {"value": 1000 * np.ones(nn), "units": "kW"},
                },
                "turbine": {
                        "control": "power",
                        "gt_idle_allowed": False,
                        #"gt_throttle": {"value": 0.5 * np.ones(nn), "units": None},
                        #"gt_power": {"value": 1000 * np.ones(nn), "units": "kW"},
                    },
                    "motor": {
                        "control": "power",
                        #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                        #"power": {"value": 1000 * np.ones(nn), "units": "kW"},
                        "rpm": {"value": np.ones((num_props,nn)) * 1790, "units": "rpm"},
                    },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "fltcond":{
                #"vs": {"value": 300.0, "units": "ft/min"},
                "Ueas": {"value": 180.0 , "units": "kn"},
                #"Utrue": {"value": 60.0, "units": "m/s"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 0.0 * np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "up", "units": None},
            },
            "trajectory":{
                #"range_initial": {"value": 0.0, "units": "NM"},
                #"fuel_used_initial": {"value": 0.0, "units": "kg"},
                #"soc_initial": {"value": 1.0, "units": None},
                "h0": {"value": 35, "units": "ft"},
                "h1": {"value": 3000, "units": "ft"},
            },
            "use_neural_net": False,
            "match_alt": True,
            "match_speed": False,
            "match_range": False,
            "duration_set": False,
            "phase_type": "unsteady_eas",
            "velocity_in": True,
            "power_in": True,
            "true_airspeed_in": False,
            "vs_in": False,
            "gamma_in": False,
            "point_analysis": False,
            "indep_nacelles": True,
            "phase_name": "climb_e",
            "speed_law": "constant_eas",
        },
    
    
        "climb_hy": { # CLIMB
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": True,
                "eq_power_nacelles_op": True,
                "const_power_profile": False,
                "s_curve_hy_profile": False,
                "eq_hy_nacelles_op": False,
                "const_hy_ratio": False,
                "prop": {
                    "prop_thrust_set": False,
                    "nacelle_power_set": True,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "relative",
                    "rule": "fixed",
                    "bias": "gt",
                    "total_mech_power_out_start": {"value": climb_pow_start_kW , "units": "kW"},
                    "total_mech_power_out_end": {"value": climb_pow_end_kW , "units": "kW"},
                    "total_mech_power_out_loc_trans": {"value": 0.5, "units": None},
                    "total_mech_power_out_w_trans": {"value": 0.2, "units": None},
                    #"hy_ratio_start": {"value": 1.0, "units": None},
                    #"hy_ratio_end": {"value": 0.0, "units": None},
                    #"hy_ratio_loc_trans": {"value": 0.96, "units": None},
                    #"hy_ratio_w_trans": {"value": 0.05, "units": None},
                    #"total_mech_power_out": {"value": np.ones((num_props,nn)) * np.array([[nac_max_cont_pow_val],[nac_max_cont_pow_val],[nac_max_cont_pow_val],[nac_max_cont_pow_val]]), "units": nac_max_cont_pow_units},
                    #"total_mech_power_out": {"value": 1122 * np.ones((num_props,nn)), "units": "kW"},
                    #"power_split_fraction_em": {"value": np.ones((num_props,nn)), "units": None},
                    #"power_split_fraction_gt": {"value": np.ones((num_props,nn)) * np.array([[0.6 * turb_op[0]],[0.6 * turb_op[1]],[0.6 * turb_op[2]],[0.6 * turb_op[3]]]), "units": None},

                    #"power_split_fraction_gt": {"value": np.ones(nn)* np.array([0.6 * turb_op[0]]), "units": None},
                    #"power_split_amount_em": {"value": 1000 * np.ones(nn), "units": "kW"},
                    "power_split_amount_gt": {"value": gt_max_cont_pow_val * np.ones((num_props,nn)) * turb_op[:,None], "units": gt_max_cont_pow_units},
                },
                "turbine": {
                        "control": "power",
                        "gt_idle_allowed": False,
                        #"gt_throttle": {"value": 0.5 * np.ones(nn), "units": None},
                        #"gt_power": {"value": 1000 * np.ones(nn), "units": "kW"},
                    },
                    "motor": {
                        "control": "power",
                        #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                        #"power": {"value": 1000 * np.ones(nn), "units": "kW"},
                        "rpm": {"value": np.ones((num_props,nn)) * 1790, "units": "rpm"},
                    },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "fltcond":{
                #"vs": {"value": np.linspace(1e-6,1500,nn), "units": "ft/min"},
                "Ueas": {"value": 180.0, "units": "kn"},
                #"Utrue": {"value": 60.0, "units": "m/s"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 0.0 * np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "up", "units": None},
            },
            "trajectory":{
                #"range_initial": {"value": 0.0, "units": "NM"},
                #"fuel_used_initial": {"value": 0.0, "units": "kg"},
                #"soc_initial": {"value": 1.0, "units": None},
                "h0": {"value": 3000, "units": "ft"},
                "h1": {"value": 10000, "units": "ft"},
            },
            "use_neural_net": False,
            "match_alt": True,
            "match_speed": False,
            "match_range": False,
            "duration_set": False,
            "phase_type": "unsteady_eas",
            "velocity_in": True,
            "power_in": True,
            "true_airspeed_in": False,
            "vs_in": False,
            "gamma_in": False,
            "point_analysis": False,
            "indep_nacelles": True,
            "phase_name": "climb_hy",
            "speed_law": "constant_eas",
        },
    
    
        "cruise_1": {  # Primary Cruise Phase. Stretches according to mission range requirements
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": False,
                "eq_power_nacelles_op": False,
                "const_power_profile": True,
                "s_curve_hy_profile": False,
                "eq_hy_nacelles_op": False,
                "const_hy_ratio": False,
                "prop": {
                    "prop_thrust_set": True,
                    "nacelle_power_set": False,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                    "thrust_share_delta": {"value": 0.0, "units": None},
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "relative",
                    "rule": cruise1_rule,
                    "bias": "gt",
                    #"total_mech_power_out": {"value": 1000 * np.ones(nn), "units": "kW"},
                    #"hy_ratio_start": {"value": 1.0, "units": None},
                    #"hy_ratio_end": {"value": 0.0, "units": None},
                    #"hy_ratio_loc_trans": {"value": 0.96, "units": None},

                    "power_split_amount_gt": {"value": np.ones((num_props,nn)) * gt_max_cont_pow_val * turb_op[:,None], "units": gt_max_cont_pow_units},
                    "power_split_fraction_gt": {"value": np.ones((num_props,nn)) * turb_op[:,None], "units": None},
                    # GT derate factor: 1.0 = full MCP, 0.5 = 50% MCP (scalar, applies to all GTs equally)
                    "gt_derate": {"value": 1.0, "units": None},
                    
                    #"power_split_fraction_gt": {"value": 0.5 * np.ones(nn), "units": None},
                    #"power_split_amount_em":{"value": np.ones((num_props,nn)) * 0.2*np.array([[em_max_cont_pow_val],[em_max_cont_pow_val],[em_max_cont_pow_val],[em_max_cont_pow_val]]), "units": em_max_cont_pow_units},
                    #"power_split_amount_gt":{"value": gt_max_cont_pow_val * np.ones(nn), "units": gt_max_cont_pow_units},
                },
                "turbine": {
                    "control": "power",
                    "gt_idle_allowed": False,
                    #"gt_throttle": None,
                    #"gt_power": None,
                },
                "motor": {
                    "control": "power",
                    #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                    #"power": None,
                    "rpm": {"value": np.ones((num_props,nn)) * 1790, "units": "rpm"},
                },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "fltcond":{
                "vs": {"value": 0 * np.ones(nn), "units": "ft/min"},
                #"Ueas": {"value": 190.0 * np.ones(nn), "units": "kn"},
                "Utrue": {"value": 235.0, "units": "kn"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 0.0 * np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "up", "units": None},
            },
            "trajectory":{
                "h0": {"value": 10000, "units": "ft"},
                "h1": {"value": 10000, "units": "ft"},
                "duration": {"value": 0.05, "units": "h"},
                "range_target": {"relative": False},
            },
            "use_neural_net": False,
            "match_alt": False,
            "match_speed": False,
            "match_range": cruise1_match_range,
            "duration_set": cruise1_duration_set,
            "phase_type": "unsteady_eas",
            "velocity_in": True,
            "power_in": False,
            "true_airspeed_in": True,
            "vs_in": True,
            "gamma_in": False,
            "point_analysis": False,
            "indep_nacelles": True,
            "phase_name": "cruise_1",
            "speed_law": "constant_tas",
        },

        "cruise_2": { ## Secondary Cruise Phase. Constant power cruise at EAS 180 kn
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": False,
                "eq_power_nacelles_op": True,
                "const_power_profile": False,
                "s_curve_hy_profile": False,
                "eq_hy_nacelles_op": False,
                "const_hy_ratio": False,
                "prop": {
                    "prop_thrust_set": True,
                    "nacelle_power_set": False,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "relative",
                    "rule": "fraction",
                    "bias": "gt",
                    #"total_mech_power_out": {"value": 1000 * np.ones(nn), "units": "kW"},
                    #"hy_ratio_start": {"value": 1.0, "units": None},
                    #"hy_ratio_end": {"value": 0.0, "units": None},
                    #"hy_ratio_loc_trans": {"value": 0.96, "units": None},
                    #"hy_ratio_w_trans": {"value": 0.05, "units": None},
                    # Independent hybridization ratio for each nacelle
                    #"hy_ratio_start_nac2": {"value": 0.95, "units": None},
                    #"hy_ratio_end_nac2": {"value": 0.95, "units": None},
                    #"hy_ratio_tau_nac2": {"value": 0.5, "units": None},
                    #"hy_ratio_trans_nac2": {"value": 0.05, "units": None},
                    #"power_split_fraction_gt_eq": {"value": 0, "units": None},
                    #"power_split_fraction_gt_nac1": {"value": 0.95, "units": None},
                    #"power_split_fraction_gt_nac2": {"value": 0.95, "units": None},
                    #"power_split_fraction_gt_nac3": {"value": 0.95, "units": None},
                    #"power_split_fraction_gt_nac4": {"value": 0.95, "units": None},
                    "power_split_fraction_gt": {"value": np.zeros((num_props,nn)) * turb_op[:,None], "units": None},
                    #"power_split_fraction_gt": {"value": 0.5 * np.ones(nn), "units": None},
                    #"power_split_amount_em":{"value": np.ones((num_props,nn)) * 0.2*np.array([[em_max_cont_pow_val],[em_max_cont_pow_val],[em_max_cont_pow_val],[em_max_cont_pow_val]]), "units": em_max_cont_pow_units},
                    #"power_split_amount_gt":{"value": gt_max_cont_pow_val * np.ones(nn), "units": gt_max_cont_pow_units},
                },
                "turbine": {
                    "control": "power",
                    "gt_idle_allowed": False,
                    #"gt_throttle": None,
                    #"gt_power": None,
                },
                "motor": {
                    "control": "power",
                    #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                    #"power": None,
                    "rpm": {"value": np.ones((num_props,nn)) * 1790, "units": "rpm"},
                },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "fltcond":{
                "vs": {"value": 0 * np.ones(nn), "units": "ft/min"},
                #"Ueas": {"value": 190.0 * np.ones(nn), "units": "kn"},
                "Utrue": {"value": 235.0, "units": "kn"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 0.0 * np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "up", "units": None},
            },
            "trajectory":{
                "h0": {"value": 10000, "units": "ft"},
                "h1": {"value": 10000, "units": "ft"},
                "duration": {"value": 0.05, "units": "h"},
                #"range_target": {"value": 1.0, "units": "NM", "relative": True},
            },
            "use_neural_net": False,
            "match_alt": False,
            "match_speed": False,
            "match_range": cruise2_match_range,
            "duration_set": cruise2_duration_set,
            "phase_type": "unsteady_eas",
            "velocity_in": True,
            "power_in": False,
            "true_airspeed_in": True,
            "vs_in": True,
            "gamma_in": False,
            "point_analysis": False,
            "indep_nacelles": True,
            "phase_name": "cruise_2",
            "speed_law": "constant_tas",
        },
    
    
        "descent": { # DESCENT
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": False,
                "eq_power_nacelles_op": True,
                "const_power_profile": False,
                "s_curve_hy_profile": False,
                "eq_hy_nacelles_op": False,
                "const_hy_ratio": False,
                "prop": {
                    "prop_thrust_set": False,
                    "nacelle_power_set": True,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "relative",
                    "rule": "fraction",
                    "bias": "em",
                    "total_mech_power_out": {"value": 0 * np.ones((num_props,nn)), "units": "kW"},
                    "power_split_fraction_em": {"value": 1 * np.ones((num_props,nn)), "units": None},
                    #"power_split_fraction_gt": {"value": np.ones((num_props,nn)) * np.array([[0.5],[0.5],[0],[0.5]]), "units": None},
                    #"power_split_amount_em": None,
                    #"power_split_amount_gt":None,
                },
                "turbine": {
                    "control": "power",
                    "gt_idle_allowed": False,
                    #"gt_throttle": None,
                    #"gt_power": None,
                },
                "motor": {
                    "control": "power",
                    #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                    #"power": None,
                    "rpm": {"value": np.ones((num_props,nn)) * 1790, "units": "rpm"},
                },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "fltcond":{
                #"vs": {"value": 0, "units": "ft/min"},
                "Ueas": {"value": 180.0, "units": "kn"},
                #"Utrue": {"value": 60.0, "units": "m/s"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 0.0 * np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "up", "units": None},
            },
            "trajectory":{
                "h0": {"value": 10000, "units": "ft"},
                "h1": {"value": 1500, "units": "ft"},
            },
            "use_neural_net": False,
            "match_alt": True,
            "match_speed": False,
            "match_range": False,
            "duration_set": False,
            "phase_type": "unsteady_eas",
            "velocity_in": True,
            "power_in": True,
            "true_airspeed_in": False,
            "vs_in": False,
            "gamma_in": False,
            "point_analysis": False,
            "indep_nacelles": True,
            "phase_name": "descent",
            "speed_law": "constant_eas",
        },
    
    
        "circuit": { # CIRCUIT
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": False,
                "eq_power_nacelles_op": True,
                "const_power_profile": False,
                "s_curve_hy_profile": False,
                "eq_hy_nacelles_op": False,
                "const_hy_ratio": False,
                "prop": {
                    "prop_thrust_set": True,
                    "nacelle_power_set": False,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                    #"diameter": {"value": 14.3 * np.ones(nn), "units": "ft"},
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "relative",
                    "rule": "fraction",
                    "bias": "em",
                    #"total_mech_power_out": None,
                    "power_split_fraction_em": {"value": (1) * np.ones((num_props,nn)), "units": None},
                    #"power_split_fraction_gt": {"value": 0.5 * np.ones(nn), "units": None},
                    #"power_split_amount_em": None,
                    #"power_split_amount_gt":None,
                },
                "turbine": {
                    "control": "power",
                    "gt_idle_allowed": False,
                    #"gt_throttle": None,
                    #"gt_power": None,
                },
                "motor": {
                    "control": "power",
                    #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                    #"power": None,
                    "rpm": {"value": np.ones((num_props,nn)) * 1790, "units": "rpm"},
                },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "fltcond":{
                "vs": {"value": 0 * np.ones(nn), "units": "ft/min"},
                "Ueas": {"value": 155.0, "units": "kn"},
                #"Utrue": {"value": 60.0, "units": "m/s"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 0.0 * np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "up", "units": None},
            },
            "trajectory":{
                "duration": {"value": 180, "units": "s"},
                "h0": {"value": 1500, "units": "ft"},
                "h1": {"value": 1500, "units": "ft"},
            },
            "use_neural_net": False,
            "match_alt": False,
            "match_speed": False,
            "match_range": False,
            "duration_set": True,
            "phase_type": "unsteady_eas",
            "velocity_in": True,
            "power_in": False,
            "true_airspeed_in": False,
            "vs_in": True,
            "gamma_in": False,
            "point_analysis": False,
            "indep_nacelles": True,
            "phase_name": "circuit",
            "speed_law": "constant_eas",
        },
        "approach": { # APPROACH
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": False,
                "eq_power_nacelles_op": True,
                "const_power_profile": False,
                "s_curve_hy_profile": False,
                "eq_hy_nacelles_op": False,
                "const_hy_ratio": False,
                "prop": {
                    "prop_thrust_set": True,
                    "nacelle_power_set": False,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "relative",
                    "rule": "fraction",
                    "bias": "em",
                    #"total_mech_power_out": {"value": 300 * np.ones(nn), "units": "kW"},
                    "power_split_fraction_em": {"value": (1) * np.ones((num_props,nn)), "units": None},
                    #"power_split_fraction_gt": {"value": 0.5 * np.ones(nn), "units": None},
                    #"power_split_amount_em": {"value": 1000 * np.ones(nn), "units": "kW"},
                    #"power_split_amount_gt": {"value": 1000 * np.ones(nn), "units": "kW"},
                },
                "turbine": {
                    "control": "power",
                    "gt_idle_allowed": False,
                    #"gt_throttle": None,
                    #"gt_power": None,
                },
                "motor": {
                    "control": "power",
                    #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                    #"power": None,
                    "rpm": {"value": np.ones((num_props,nn)) * 1790, "units": "rpm"},
                },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "fltcond":{
                #"vs": {"value": -636 * np.ones(nn), "units": "ft/min"},
                "gamma": {"value": -3.0 * np.ones(nn), "units": "deg"},
                "Ueas": {"value": 130.0, "units": "kn"},
                #"Utrue": {"value": 60.0, "units": "m/s"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 35 * np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "down", "units": None},
            },
            "trajectory":{
                #"range_initial": {"value": 0.0, "units": "NM"},
                #"fuel_used_initial": {"value": 0.0, "units": "kg"},
                #"soc_initial": {"value": 1.0, "units": None},
                "h0": {"value": 1500, "units": "ft"},
                "h1": {"value": 50, "units": "ft"},
            },
            "use_neural_net": False,
            "match_alt": True,
            "match_speed": False,
            "match_range": False,
            "duration_set": False,
            "phase_type": "unsteady_eas",
            "velocity_in": True,
            "power_in": False,
            "true_airspeed_in": False,
            "vs_in": False,
            "gamma_in": True,
            "point_analysis": False,
            "indep_nacelles": True,
            "phase_name": "approach",
            "speed_law": "constant_eas",
        },
    
    
        "reserve_go_around": { # RESERVE GO AROUND
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": False,
                "eq_power_nacelles_op": True,
                "const_power_profile": False,
                "s_curve_hy_profile": False,
                "eq_hy_nacelles_op": False,
                "const_hy_ratio": False,
                "prop": {
                    "prop_thrust_set": False,
                    "nacelle_power_set": True,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "relative",
                    "rule": "fraction",
                    "bias": "em",
                    #"throttle": {"value": 0.7, "units": None},
                    "total_mech_power_out": {"value": em_max_cont_pow_val * np.ones((num_props,nn)), "units": em_mtop_pow_units},
                    "power_split_fraction_em": {"value": (1) * np.ones((num_props,nn)), "units": None},
                    #"power_split_fraction_gt": {"value": 0.5 * np.ones(nn), "units": None},
                    #"power_split_amount_em": None,
                    #"power_split_amount_gt":None,
                },
                "turbine": {
                    "control": "power",
                    "gt_idle_allowed": False,
                    #"gt_throttle": None,
                    #"gt_power": None,
                },
                "motor": {
                    "control": "power",
                    #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                    #"power": None,
                    "rpm": {"value": np.ones((num_props,nn)) * 1790, "units": "rpm"},
                },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "fltcond":{
                #"vs": {"value": 0 * np.ones(nn), "units": "ft/min"},
                "Ueas": {"value": 130.0, "units": "kn"},
                #"Utrue": {"value": 60.0, "units": "m/s"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 0.0 * np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "up", "units": None},
            },
            "trajectory":{
                "h0": {"value": 0, "units": "ft"},
                "h1": {"value": 3500, "units": "ft"},
            },
            "use_neural_net": False,
            "match_alt": True,
            "match_speed": False,
            "match_range": False,
            "duration_set": False,
            "phase_type": "unsteady_eas",
            "velocity_in": True,
            "power_in": True,
            "true_airspeed_in": False,
            "vs_in": False,
            "gamma_in": False,
            "point_analysis": False,
            "indep_nacelles": True,
            "phase_name": "reserve_go_around",
            "speed_law": "constant_eas",
        },
    
        "reserve_climb": {
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": False,
                "eq_power_nacelles_op": True,
                "const_power_profile": False,
                "s_curve_hy_profile": False,
                "eq_hy_nacelles_op": False,
                "const_hy_ratio": False,
                "prop": {
                    "prop_thrust_set": False,
                    "nacelle_power_set": True,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "independent",
                    "rule": "amount",
                    "bias": "gt",
                    #"throttle": {"value": 0.7, "units": None},
                    #"total_mech_power_out": {"value": nac_max_cont_pow_val * np.ones((num_props,nn)), "units": nac_max_cont_pow_units},
                    #"power_split_fraction_em": None,
                    #"power_split_fraction_gt": {"value": np.ones((num_props,nn)) * np.array([[0.99],[0.5],[0.5],[0.5]]), "units": None},
                    #"power_split_amount_em": None,
                    "power_split_amount_gt":{"value": gt_max_cont_pow_val * np.ones((num_props,nn)), "units": gt_max_cont_pow_units},
                },
                "turbine": {
                    "control": "power",
                    "gt_idle_allowed": False,
                    #"gt_throttle": None,
                    "power": {"value": gt_max_cont_pow_val * np.ones((num_props,nn)), "units": gt_max_cont_pow_units},
                },
                "motor": {
                    "control": "power",
                    #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                    "power": {"value": 420.246 * np.ones((num_props,nn)), "units": "kW"},
                    "rpm": {"value": np.ones((num_props,nn)) * 1790, "units": "rpm"},
                },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "fltcond":{
                #"vs": {"value": 0, "units": "ft/min"},
                "Ueas": {"value": 180.0, "units": "kn"},
                #"Utrue": {"value": 60.0, "units": "m/s"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 0.0 * np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "up", "units": None},
            },
            "trajectory":{
                #"range_initial": {"value": 0.0, "units": "NM"},
                #"fuel_used_initial": {"value": 0.0, "units": "kg"},
                #"soc_initial": {"value": 1.0, "units": None},
                "h0": {"value": 3500, "units": "ft"},
                "h1": {"value": 8000, "units": "ft"},
            },
            "use_neural_net": False,
            "match_alt": True,
            "match_speed": False,
            "match_range": False,
            "duration_set": False,
            "phase_type": "unsteady_eas",
            "velocity_in": True,
            "power_in": True,
            "true_airspeed_in": False,
            "vs_in": False,
            "gamma_in": False,
            "point_analysis": False,
            "indep_nacelles": True,
            "phase_name": "reserve_climb",
            "speed_law": "constant_eas",
        },
    
    
        "reserve_cruise": {
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": False,
                "eq_power_nacelles_op": True,
                "const_power_profile": False,
                "s_curve_hy_profile": False,
                "eq_hy_nacelles_op": False,
                "const_hy_ratio": False,
                "prop": {
                    "prop_thrust_set": True,
                    "nacelle_power_set": False,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "relative",
                    "rule": "fraction",
                    "bias": "gt",
                    #"total_mech_power_out": None,
                    #"power_split_fraction_em": None,
                    "power_split_fraction_gt": {"value": 1 * np.ones((num_props,nn)), "units": None},
                    #"power_split_amount_em": None,
                    #"power_split_amount_gt":None,
                },
                "turbine": {
                    "control": "power",
                    "gt_idle_allowed": False,
                    #"gt_throttle": None,
                    #"gt_power": None,
                },
                "motor": {
                    "control": "power",
                    #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                    #"power": None,
                    "rpm": {"value": np.ones((num_props,nn)) * 1790, "units": "rpm"},
                },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "fltcond":{
                "vs": {"value": 0 * np.ones(nn), "units": "ft/min"},
                "Ueas": {"value": 170.0, "units": "kn"},
                #"Utrue": {"value": 60.0, "units": "m/s"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 0.0 * np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "up", "units": None},
            },
            "trajectory":{
                "range_initial": {"value": 0.0, "units": "NM"},
                "fuel_used_initial": {"value": 0.0, "units": "kg"},
                "soc_initial": {"value": 1.0, "units": None},
                "h0": {"value": 8000, "units": "ft"},
                "h1": {"value": 8000, "units": "ft"},
                "range_target": {"relative": False},

            },
            "use_neural_net": False,
            "match_alt": False,
            "match_speed": False,
            "match_range": True,
            "duration_set": False,
            "phase_type": "unsteady_eas",
            "velocity_in": True,
            "power_in": False,
            "true_airspeed_in": False,
            "vs_in": True,
            "gamma_in": False,
            "point_analysis": False,
            "indep_nacelles": True,
            "phase_name": "reserve_cruise",
            "speed_law": "constant_eas",
        },
    
    
        "reserve_descent": { # RESERVE DESCENT
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": False,
                "eq_power_nacelles_op": True,
                "const_power_profile": False,
                "s_curve_hy_profile": False,
                "eq_hy_nacelles_op": False,
                "const_hy_ratio": False,
                "prop": {
                    "prop_thrust_set": False,
                    "nacelle_power_set": True,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "independent",
                    "rule": "fraction",
                    "bias": "gt",
                    "total_mech_power_out": {"value": 0 * np.ones((num_props,nn)), "units": "kW"},
                    #"power_split_fraction_em": None,
                    "power_split_fraction_gt": {"value": 1 * np.ones((num_props,nn)), "units": None},
                    #"power_split_amount_em": None,
                    #"power_split_amount_gt":None,
                },
                "turbine": {
                    "control": "throttle",
                    "gt_idle_allowed": True,
                    "throttle": {"value": 0.0 * np.ones((num_props,nn)), "units": None},
                    #"gt_power": None,
                    },
                    "motor": {
                        "control": "power",
                        #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                        "power": {"value": 0 * np.ones((num_props,nn)), "units": "kW"},
                        "rpm": {"value": np.ones((num_props,nn)) * 1790, "units": "rpm"},
                    },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "fltcond":{
                #"vs": {"value": 0, "units": "ft/min"},
                "Ueas": {"value": 180.0, "units": "kn"},
                #"Utrue": {"value": 60.0, "units": "m/s"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 0.0 * np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "up", "units": None},
            },
            "trajectory":{
                #"range_initial": {"value": 0.0, "units": "NM"},
                #"fuel_used_initial": {"value": 0.0, "units": "kg"},
                #"soc_initial": {"value": 1.0, "units": None},
                "h0": {"value": 8000, "units": "ft"},
                "h1": {"value": 1500, "units": "ft"},
            },
            "use_neural_net": False,
            "match_alt": True,
            "match_speed": False,
            "match_range": False,
            "duration_set": False,
            "phase_type": "unsteady_eas",
            "velocity_in": True,
            "power_in": True,
            "true_airspeed_in": False,
            "vs_in": False,
            "gamma_in": False,
            "point_analysis": False,
            "indep_nacelles": True,
            "phase_name": "reserve_descent",
            "speed_law": "constant_eas",
        },
        "reserve_circuit": {
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": False,
                "eq_power_nacelles_op": True,
                "const_power_profile": False,
                "s_curve_hy_profile": False,
                "eq_hy_nacelles_op": False,
                "const_hy_ratio": False,
                "prop": {
                    "prop_thrust_set": True,
                    "nacelle_power_set": False,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "relative",
                    "rule": "fraction",
                    "bias": "gt",
                    #"total_mech_power_out": None,
                    #"power_split_fraction_em": None,
                    "power_split_fraction_gt": {"value": 1 * np.ones((num_props,nn)), "units": None},
                    #"power_split_amount_em": None,
                    #"power_split_amount_gt":None,
                },
                "turbine": {
                    "control": "power",
                    "gt_idle_allowed": False,
                    #"gt_throttle": None,
                    #"gt_power": None,
                    },
                    "motor": {
                        "control": "power",
                        #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                        #"power": None,
                        "rpm": {"value": np.ones((num_props,nn)) * 1790, "units": "rpm"},
                    },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "fltcond":{
                "vs": {"value": 0 * np.ones(nn), "units": "ft/min"},
                "Ueas": {"value": 155.0, "units": "kn"},
                #"Utrue": {"value": 60.0, "units": "m/s"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 0.0 * np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "up", "units": None},
            },
            "trajectory":{
                #"range_initial": {"value": 0.0, "units": "NM"},
                #"fuel_used_initial": {"value": 0.0, "units": "kg"},
                #"soc_initial": {"value": 1.0, "units": None},
                "h0": {"value": 1500, "units": "ft"},
                "h1": {"value": 1500, "units": "ft"},
                "duration": {"value": 180, "units": "s"},
            },
            "use_neural_net": False,
            "match_alt": False,
            "match_speed": False,
            "match_range": False,
            "duration_set": True,
            "phase_type": "unsteady_eas",
            "velocity_in": True,
            "power_in": False,
            "true_airspeed_in": False,
            "vs_in": True,
            "gamma_in": False,
            "point_analysis": False,
            "indep_nacelles": True,
            "phase_name": "reserve_circuit",
            "speed_law": "constant_eas",
        },
        "reserve_approach": {
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": False,
                "eq_power_nacelles_op": True,
                "const_power_profile": False,
                "s_curve_hy_profile": False,
                "eq_hy_nacelles_op": False,
                "const_hy_ratio": False,
                "prop": {
                    "prop_thrust_set": True,
                    "nacelle_power_set": False,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "relative",
                    "rule": "fraction",
                    "bias": "gt",
                    #"total_mech_power_out": None,
                    #"power_split_fraction_em": {"value": (1 - 1e-6) * np.ones(nn), "units": None},
                    "power_split_fraction_gt": {"value": (1) * np.ones((num_props,nn)), "units": None},
                    #"power_split_amount_em": {"value": 1000 * np.ones(nn), "units": "kW"},
                    #"power_split_amount_gt": {"value": 1000 * np.ones(nn), "units": "kW"},
                },
                "turbine": {
                        "control": "power",
                        "gt_idle_allowed": False,
                        #"gt_throttle": None,
                        #"gt_power": None,
                    },
                    "motor": {
                        "control": "power",
                        #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                        #"power": None,
                        "rpm": {"value": np.ones((num_props,nn)) * 1790, "units": "rpm"},
                    },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "fltcond":{
                #"vs": {"value": -636, "units": "ft/min"},
                "gamma": {"value": -3 * np.ones(nn), "units": "deg"},
                "Ueas": {"value": 120.0, "units": "kn"},
                #"Utrue": {"value": 60.0, "units": "m/s"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 35* np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "down", "units": None},
            },
            "trajectory":{
                #"range_initial": {"value": 0.0, "units": "NM"},
                #"fuel_used_initial": {"value": 0.0, "units": "kg"},
                #"soc_initial": {"value": 1.0, "units": None},
                "h0": {"value": 1500, "units": "ft"},
                "h1": {"value": 50, "units": "ft"},
                #"duration": {"value": 180, "units": "s"},
            },
            "use_neural_net": False,
            "match_alt": True,
            "match_speed": False,
            "match_range": False,
            "duration_set": False,
            "phase_type": "unsteady_eas",
            "velocity_in": True,
            "power_in": False,
            "true_airspeed_in": False,
            "vs_in": False,
            "gamma_in": True,
            "point_analysis": False,
            "indep_nacelles": True,
            "phase_name": "reserve_approach",
            "speed_law": "constant_eas",
        },
        "reserve_taxi_in": {
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": False,
                "eq_power_nacelles_op": True,
                "const_power_profile": False,
                "s_curve_hy_profile": False,
                "eq_hy_nacelles_op": False,
                "const_hy_ratio": False,
                "prop": {
                    "prop_thrust_set": False,
                    "nacelle_power_set": True,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "relative",
                    "rule": "fraction",
                    "bias": "gt",
                    "total_mech_power_out": {"value": 40 * np.ones((num_props,nn)), "units": "kW"},
                    "throttle": {"value": 0.05 * np.ones((num_props,nn)), "units": None},
                    #"power_split_fraction_em": {"value": np.ones((num_props,nn)) * np.array([[1 - 1e-6],[1 - 1e-6],[1 - 1e-6],[1 - 1e-6]]), "units": None},
                    "power_split_fraction_gt": {"value": 0 * np.ones((num_props,nn)), "units": None},
                    "power_split_amount_em": None,
                    "power_split_amount_gt":None,
                },
                "turbine": {
                        "control": "power",
                        "gt_idle_allowed": False,
                        #"gt_throttle": None,
                        #"gt_power": None,
                    },
                    "motor": {
                        "control": "power",
                        #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                        #"power": None,
                        "rpm": {"value": np.ones((num_props,nn)) * 1790, "units": "rpm"},
                    },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "battery":{
                "q_cool_bat": {"value": 25 * np.ones(nn), "units": "kW"},
            },
            "fltcond":{
                "vs": {"value": 0 * np.ones(nn), "units": "ft/min"},
                "Ueas": {"value": 25.0, "units": "kn"},
                #"Utrue": {"value": 60.0, "units": "m/s"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 0.0 * np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "down", "units": None},
            },
            "trajectory":{
                #"range_initial": {"value": 0.0, "units": "NM"},
                #"fuel_used_initial": {"value": 0.0, "units": "kg"},
                #"soc_initial": {"value": 1.0, "units": None},
                "h0": {"value": 50, "units": "ft"},
                "h1": {"value": 50, "units": "ft"},
                "duration": {"value": 300, "units": "s"},
            },
            "use_neural_net": False,
            "match_alt": False,
            "match_speed": False,
            "match_range": False,
            "duration_set": True,
            "phase_type": "power_only",
            "velocity_in": True,
            "power_in": True,
            "true_airspeed_in": False,
            "vs_in": True,
            "gamma_in": False,
            "point_analysis": False,
            "indep_nacelles": True,
            "phase_name": "reserve_taxi_in",
            "speed_law": "constant_eas",
        },
        "holding_cruise": {
            "propulsion":{
                "nac_op_array": np.ones((num_props, nn)),
                "s_curve_power_profile": False,
                "eq_power_nacelles_op": True,
                "const_power_profile": False,
                "s_curve_hy_profile": False,
                "eq_hy_nacelles_op": False,
                "const_hy_ratio": False,
                "prop": {
                    "prop_thrust_set": True,
                    "nacelle_power_set": False,
                    "prop_rpm_set": False,
                    "thrust_share": np.array([np.ones(nn),np.ones(nn),np.ones(nn),np.ones(nn)]),
                },
                "nacelle": {
                    "command": "power",
                    "power_spec": "relative",
                    "rule": "fraction",
                    "bias": "gt",
                    #"total_mech_power_out": None,
                    #"power_split_fraction_em": None,
                    "power_split_fraction_gt": {"value": (1) * np.ones((num_props,nn)), "units": None},
                    #"power_split_amount_em": None,
                    #"power_split_amount_gt":None,
                },
                "turbine": {
                    "control": "power",
                    "gt_idle_allowed": False,
                    #"gt_throttle": None,
                    #"gt_power": None,
                    },
                    "motor": {
                        "control": "power",
                        #"torque": {"value": 1000 * np.ones(nn), "units": "Nm"},
                        #"power": None,
                        "rpm": {"value": np.ones((num_props,nn)) * 1790, "units": "rpm"},
                    },
                "eta_parc": {"value": 1.0 * np.ones(nn), "units": None},
            },
            "fltcond":{
                "vs": {"value": 0 * np.ones(nn), "units": "ft/min"},
                "Ueas": {"value": 165.0, "units": "kn"},
                #"Utrue": {"value": 60.0, "units": "m/s"},
                "disa": {"value": 0.0 * np.ones(nn), "units": "degC"},
                "flap_angle": {"value": 0.0 * np.ones(nn), "units": "deg"},
                "gear_pos": {"value": "up", "units": None},
            },
            "trajectory":{
                #"range_initial": {"value": 0.0, "units": "NM"},
                #"fuel_used_initial": {"value": 0.0, "units": "kg"},
                #"soc_initial": {"value": 1.0, "units": None},
                "h0": {"value": hld_crz_h_ft, "units": "ft"},
                "h1": {"value": hld_crz_h_ft, "units": "ft"},
                "duration": {"value": hld_crz_dur_min * 60, "units": "s"},
            },
            "use_neural_net": False,
            "match_alt": False,
            "match_speed": False,
            "match_range": False,
            "duration_set": True,
            "phase_type": "unsteady_eas",
            "velocity_in": True,
            "power_in": False,
            "true_airspeed_in": False,
            "vs_in": True,
            "gamma_in": False,
            "point_analysis": False,
            "indep_nacelles": True,
            "phase_name": "holding_cruise",
            "speed_law": "constant_eas",
        },
    
    }

    # ----- Checking the power train configuration -----


    check_mission_config(mission_config, num_props=num_props)
    
    return mission_config